
export const GET_ITEMS_SUCCESS='GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAILED='GET_ITEMS_FAILED'
export const SET_TYPE_HEADINGS = 'SET_TYPE_HEADINGS';

export const SET_CURRENT_INGREDIENT='SET_CURRENT_INGREDIENT' 
export const CLEAR_CURRENT_INGREDIENT = 'CLEAR_CURRENT_INGREDIENT';

export const ADD_INGREDIENT_TO_CONSTRUCTOR = 'ADD_INGREDIENT_TO_CONSTRUCTOR';
export const REMOVE_INGREDIENT_FROM_CONSTRUCTOR = 'REMOVE_INGREDIENT_FROM_CONSTRUCTOR';
export const REMOVE_ALL_BUNS_FROM_CONSTRUCTOR = 'REMOVE_ALL_BUNS_FROM_CONSTRUCTOR';
export const UPDATE_INGREDIENT_ORDER = 'UPDATE_INGREDIENT_ORDER';
export const REMOVE_ALL_INGREDIENTS_FROM_CONSTRUCTOR = 'REMOVE_ALL_INGREDIENTS_FROM_CONSTRUCTOR';


export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAILED = 'PLACE_ORDER_FAILED';